name: GithubExample # The name of the App
options: # Some general settings for the project
  createIntermediateGroups: true # If the folders are nested, also nest the groups in Xcode
  indentWidth: 2 # indent by 2 spaces
  tabWidth: 2 # a tab is 2 spaces
  bundleIdPrefix: "com.github.jmlb23"
packages:
    Kingfisher:
      url: https://github.com/onevcat/Kingfisher.git
      from: 6.2.1
targets: # The List of our targets
  GithubExample:
    type: application
    platform: iOS
    deploymentTarget: "14.0"
    preBuildScripts:
      - script: cd "$SRCROOT/../.." ; ./gradlew :state:embedAndSignAppleFrameworkForXcode
        name: Gradle
    sources:
      - path: GithubExample
    settings:
      configs:
        debug:
          FRAMEWORK_SEARCH_PATHS: "$SRCROOT/../../state/build/xcode-frameworks/$(CONFIGURATION)/$(SDK_NAME)/"
          OTHER_LDFLAGS: "$(inherited) -framework State"
        release:
          FRAMEWORK_SEARCH_PATHS: "$SRCROOT/../../mvvm/build/xcode-frameworks/$(CONFIGURATION)/$(SDK_NAME)/"
          OTHER_LDFLAGS: "$(inherited) -framework State"
    dependencies:
        - package: Kingfisher
        - sdk: SwiftUI.framework
    info:
      path: Info.plist
      version: 1
      properties:
        UILaunchScreen: ""
        UIApplicationSupportsIndirectInputEvents: YES
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: YES
        UISupportedInterfaceOrientations~iphone:
          [UIInterfaceOrientationPortrait, UIInterfaceOrientationLandscapeLeft, UIInterfaceOrientationLandscapeRight]
        UISupportedInterfaceOrientations~ipad:
          [UIInterfaceOrientationPortrait, UIInterfaceOrientationPortraitUpsideDown, UIInterfaceOrientationLandscapeLeft, UIInterfaceOrientationLandscapeRight]
